---

name: Checks

on: [push]

services:
 services:
  db:
    build:
      dockerfile: ./Dockerfile.db
      context: ./db
    restart: always
    container_name: postgres_db
    volumes:
      - ./:/usr/src/app:ro
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=codemonk_user
      - POSTGRES_PASSWORD=codemonk_password
      - POSTGRES_DB=codemonk_db_dev

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: docker-compose run --rm api sh -c "pytest"
      - name: Lint
        run: docker-compose run --rm api sh -c "flake8"

volumes:
  pg_data: